apiVersion: v1
kind: Service
metadata:
  name: image-analysis
  namespace: a1-app
spec:
  selector:
    app: image-analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
