apiVersion: apps/v1
kind: Deployment
metadata:
  name: directory
  namespace: cloud-storage
  labels:
    app: directory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directory
  template:
    metadata:
      labels:
        app: directory
    spec:
      containers:
        - name: directory
          image: rusxl/cloud-storage-directory:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: BUCKET_COUNT
              value: "2"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: directory
  namespace: cloud-storage
spec:
  type: NodePort
  selector:
    app: directory
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
