apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-analysis
  namespace: a1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-analysis
  template:
    metadata:
      labels:
        app: image-analysis
    spec:
      containers:
        - name: image-analysis
          image: ccuni/image-analysis-service-2025w
          readinessProbe:
            httpGet:
              path: /readinessProbe
              port: 80
            timeoutSeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /livenessProbe
              port: 80
            timeoutSeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: "550m"
              memory: "700Mi"
            limits:
              cpu: "1000m"
              memory: "850Mi"
