apiVersion: apps/v1
kind: Deployment
metadata:
  name: section
  namespace: a1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: section
  template:
    metadata:
      labels:
        app: section
    spec:
      containers:
        - name: section
          image: ccuni/section-service-2025w
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /readinessProbe
              port: 80
          livenessProbe:
            httpGet:
              path: /livenessProbe
              port: 80
          resources:
            requests:
              cpu: "10m"
              memory: "130Mi"
            limits:
              cpu: "100m"
              memory: "175Mi"
          env:
            - name: EXTERNAL_MONGODB_URL
              value: "mongodb://mongo:27017"
