apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recognition
  namespace: a1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-recognition
  template:
    metadata:
      labels:
        app: face-recognition
    spec:
      containers:
        - name: face-recognition
          image: ccuni/face-recognition-service-2025w
          readinessProbe:
            httpGet:
              path: /readinessProbe
              port: 80
          livenessProbe:
            httpGet:
              path: /livenessProbe
              port: 80
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
