apiVersion: apps/v1
kind: Deployment
metadata:
  name: section
  namespace: a1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: section
  template:
    metadata:
      labels:
        app: section
    spec:
      containers:
        - name: section
          image: ccuni/section-service-2025w
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /readinessProbe
              port: 80
          livenessProbe:
            httpGet:
              path: /livenessProbe
              port: 80
          resources:
            limits:
              cpu: "0.25"
              memory: "256Mi"
          env:
            - name: EXTERNAL_MONGODB_URL
              value: "mongodb://localhost:27017"
        - name: mongo
          image: mongodb/mongodb-community-server:7.0-ubi8
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-pv
              mountPath: /data/db
      volumes:
        - name: mongo-pv
          persistentVolumeClaim:
            claimName: mongo-pvc
