apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: a1-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /camera/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: camera
                port:
                  number: 80
          - path: /section/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: section
                port:
                  number: 80
          - path: /alert/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: alert
                port:
                  number: 80
